import { StyleSheet } from 'react-native';
import type { Theme } from '@/constants/colors';
import { radius, spacing } from '@/constants/commonStyles';

export const makeStyles = (theme: Theme) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: theme.surface,
    },
    centeredFill: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing[6],
    },
    emptyText: {
      color: theme.inkMuted,
      fontSize: 13,
      textAlign: 'center',
      marginTop: spacing[3],
    },
    scrollContent: {
      padding: spacing[4],
      paddingBottom: 120,
    },
    banner: {
      backgroundColor: theme.primaryMuted,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: 'rgba(232,104,26,0.3)',
      padding: spacing[3.5],
      flexDirection: 'row',
      alignItems: 'flex-start',
    },
    bannerText: {
      flex: 1,
      marginLeft: spacing[2],
      color: theme.primary,
      fontSize: 13,
      lineHeight: 20,
    },
    itemsCard: {
      backgroundColor: theme.card,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: theme.hair,
      marginTop: spacing[4],
      overflow: 'hidden',
    },
    itemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: spacing[3.5],
    },
    itemRowDivider: {
      borderBottomWidth: 1,
      borderBottomColor: theme.hair,
    },
    itemBody: {
      flex: 1,
    },
    itemName: {
      color: theme.ink,
      fontSize: 13,
    },
    itemQty: {
      color: theme.inkMuted,
      fontSize: 11,
      marginTop: 2,
    },
    itemPrice: {
      color: theme.ink,
      fontSize: 13,
      fontWeight: '700',
    },
    draftCard: {
      backgroundColor: theme.card,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: theme.hair,
      padding: spacing[4],
      marginTop: spacing[3],
    },
    draftHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing[2],
    },
    draftTitle: {
      color: theme.ink,
      fontSize: 13,
      fontWeight: '700',
    },
    addRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: spacing[3],
      marginTop: spacing[3],
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.primary,
      gap: spacing[2],
    },
    addRowText: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: '700',
    },
    totalCard: {
      backgroundColor: theme.card,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: theme.hair,
      padding: spacing[4],
      marginTop: spacing[4],
    },
    totalRow: {
      flexDirection: 'row',
    },
    totalRowSpaced: {
      marginTop: spacing[2],
    },
    totalLabel: {
      flex: 1,
      color: theme.ink,
      fontSize: 14,
      fontWeight: '700',
    },
    totalValue: {
      color: theme.primary,
      fontSize: 16,
      fontWeight: '700',
    },
    receiptCard: {
      backgroundColor: theme.card,
      borderRadius: radius['2xl'],
      borderWidth: 1,
      borderColor: theme.hair,
      padding: spacing[4],
      marginTop: spacing[3],
    },
    receiptTitle: {
      color: theme.ink,
      fontSize: 14,
      fontWeight: '700',
      marginBottom: spacing[3],
    },
    receiptImage: {
      width: '100%',
      height: 220,
      borderRadius: radius.lg,
      backgroundColor: theme.surface,
    },
    uploadBox: {
      height: 160,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.hair,
      backgroundColor: theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: spacing[3],
      overflow: 'hidden',
    },
    uploadPreview: {
      width: '100%',
      height: '100%',
    },
    uploadHint: {
      color: theme.inkMuted,
      fontSize: 12,
      marginTop: spacing[2],
    },
    footer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: theme.card,
      borderTopWidth: 1,
      borderTopColor: theme.hair,
      paddingHorizontal: spacing[4],
      paddingVertical: spacing[3],
      paddingBottom: spacing[4],
    },
  });
